version: "3.2"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db_data:/config
    ports:
      - "3306:3306"
    networks:
      - internal

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
    ports:
      - "82:82"
    depends_on:
      - mariadb
    networks:
      - internal

  glpi:
    image: diouxx/glpi
    container_name: glpi
    hostname: glpi
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/var/www/html/glpi
      - ./crontab.txt:/var/spool/cron/crontabs/root
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true
      - traefik.http.services.glpi.loadbalancer.server.port=80
      - traefik.http.routers.glpi.entrypoints=web
      - traefik.http.routers.glpi.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.glpi-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.glpi.middlewares=glpi-https-redirect
      - traefik.http.routers.glpi-secure.entrypoints=websecure
      - traefik.http.routers.glpi-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.glpi-secure.tls=true
    environment:
      - TIMEZONE=Europe/Madrid
    restart: always
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    external: true
