version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx-xxxxxxxx-xxxxxxx
      - ZONE=example.com
      - PROXIED=true
