version: '3'

networks:
  internal:
    external: true
  proxy:
    external: true

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - internal

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
      - 'traefik.http.routers.nextcloud.entrypoints=web'
      - 'traefik.http.routers.nextcloud.rule=Host(`${FQDN}`)'
#      - 'traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=websecure'
      - 'traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect'
      - 'traefik.http.routers.nextcloud-secure.entrypoints=websecure'
      - 'traefik.http.routers.nextcloud-secure.rule=Host(`${FQDN}`)'
      - 'traefik.http.routers.nextcloud-secure.tls=true'
#      - "traefik.http.middlewares.nextcloud-sts.headers.stsSeconds=31536000"
#      - "traefik.http.middlewares.nextcloud-sts.headers.stsIncludeSubdomains=true"
#      - "traefik.http.middlewares.nextcloud-sts.headers.stsPreload=true"
#      - "traefik.http.middlewares.nextcloud-chain.chain.middlewares=https-redirect@file,nex>
#      - "traefik.http.routers.nextcloud-secure.middlewares=basicauth"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
    depends_on:
      - app
    networks:
      - internal
      - proxy

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - redis
    networks:
      - internal