version: '3'

networks:
  rustdesk-net:
    external: false
  #proxy:
    #external: true

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r ejemplo.com:21117
    #command: hbbs -r ejemplo.com:21117
    volumes:
      - ./data:/root
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.rustdesk.rule=Host(`ejemplo.com`)"
      #- "traefik.http.services.rustdesk.loadbalancer.server.port=80"
    networks:
      - rustdesk-net
      #- proxy
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
      #- proxy
    restart: unless-stopped
